# Generated by Django 3.0.4 on 2020-03-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDataSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('info', models.TextField()),
                ('date', models.DateTimeField()),
                ('kws', models.CharField(max_length=50)),
                ('cited', models.PositiveIntegerField()),
                ('downed', models.PositiveIntegerField()),
                ('download', models.URLField()),
                ('abstract', models.TextField()),
                ('fund', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'idata spider',
            },
        ),
    ]
