# Generated by Django 3.0.4 on 2020-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originkws', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=3)),
                ('body', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendkws', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Simplesearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('info', models.TextField()),
                ('date', models.TextField()),
                ('kws', models.CharField(max_length=50)),
                ('cited', models.PositiveIntegerField()),
                ('downed', models.PositiveIntegerField()),
                ('download', models.URLField()),
                ('abstract', models.TextField()),
                ('fund', models.TextField()),
            ],
        ),
    ]
