# Generated by Django 3.0.4 on 2020-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('info', models.TextField()),
                ('date', models.TextField()),
                ('kws', models.CharField(max_length=50)),
                ('cited', models.TextField()),
                ('downed', models.TextField()),
                ('download', models.TextField()),
                ('abstract', models.TextField()),
                ('fund', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='simplesearch',
            name='cited',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simplesearch',
            name='downed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simplesearch',
            name='download',
            field=models.TextField(),
        ),
    ]
