# Generated by Django 3.0.4 on 2020-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0002_auto_20200420_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.TextField()),
                ('record_db', models.TextField()),
            ],
        ),
    ]
