# Generated by Django 3.0.4 on 2020-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0004_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='flag',
            field=models.TextField(default='', editable=False),
        ),
    ]
