# Generated by Django 3.0.4 on 2020-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0007_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.TextField()),
            ],
        ),
    ]
