# Generated by Django 3.0.4 on 2020-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0008_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='folder',
            field=models.TextField(default='', editable=False),
        ),
    ]
