# Generated by Django 3.0.4 on 2020-05-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0010_auto_20200501_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadcorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_name', models.TextField(max_length=30)),
                ('corpus_kws', models.TextField(max_length=200)),
            ],
        ),
    ]
