# Generated by Django 3.0.4 on 2020-05-03 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0011_uploadcorpus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadcorpus',
            options={'ordering': ('-create_timestamp',)},
        ),
        migrations.AddField(
            model_name='uploadcorpus',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 9, 50, 34, 902905)),
        ),
    ]
