# Generated by Django 3.0.4 on 2020-05-03 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0012_auto_20200503_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcorpus',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 10, 13, 57, 136677, tzinfo=utc)),
        ),
    ]
