# Generated by Django 3.0.4 on 2020-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0013_auto_20200503_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcorpus',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
