# Generated by Django 3.0.4 on 2020-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0014_auto_20200503_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filerepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='detailsearch',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detailsearch',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
