# Generated by Django 3.0.4 on 2020-05-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0016_project_projectinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.TextField()),
                ('job', models.TextField()),
                ('place', models.TextField()),
                ('email', models.TextField()),
                ('sign', models.TextField()),
            ],
        ),
    ]
