# Generated by Django 3.0.4 on 2020-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0017_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
