# Generated by Django 3.0.4 on 2020-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0018_personal_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='corpus',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='subrepo',
            field=models.TextField(default=''),
        ),
    ]
